sudo: true
language: python
python:
- '3.4'
- '3.5'
- '3.6'
services:
  - docker
env:
  global:
  - PYPI_USERNAME=WTRMQDev
  - secure: "Ua1ruJkaRdmIBgAQJYURw6v4LxSvGqtTX37HbwCPePqURGWSuQP36LDWwO5CjhCJuF9lJpqiTcAAqaFLUs0MzDg1EPv6lVfv+6JxCqtCUQ1BD2jPJOJ9HC6kxqapVJziXlknnDJIcTxUKDwd4he2VlJiBMYv8q4/Rq4Xw33aSkbECXZdNZYjucRhgoKMwf50fsxD1vwbgDd6617nA1TaUdVdzOAgpoM1J0pYkG8Rk5lJ/yO3AKjyieP5vEofVjkj2Zh6jjD5W8yxkwMHCImvZU4FC0TyyD2wxiRk3MwMeVY9EB3DzjrggatRQsyP7T89Ja0Qwk5TB/Q1wT/MExD7gRo66mFaobcQ/ygPhcVuDBWa/pONtQdFkEuKLOgfTsHADrK6Z7VTy/gwkepkycZ5B5RzgX/o4LKUiVlSUI7ilBxrEBmCDQ5rZOci4C1tNgAsC+mpDvkkGGIF7/RvWAr2vo0qyzV54GGeN65ivASKIMCFQUOVxmVyGSex92c62UVx2TjuN06n2t2Ne24wvpPDwYmtH0XgZQi0Lnd6l+aFGMloiA0dKMLUs+8Onrw9UC6X2wwoMq1B0E3NIletUn3gt00meqRywKFKsEggxqP36mFfpzlB5cRcWdLoQGeYVuIky3uDrwp/CFwU7zc30rk387l0qwvfR9z7n8GKzfV+ACg="
  - WHEELBUILDER_IMAGE=quay.io/pypa/manylinux2010_x86_64
addons:
  apt:
    packages:
    - git
    - libtool
    - autoconf
    - automake
    - pkg-config
    - libffi-dev
    - libgmp-dev
before_install:
- source .travis/install.sh
install:
- python setup.py bdist_wheel
script:
- bash .travis/run_tests.sh
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x .travis/*.sh && .travis/deploy.sh
  on:
    tags: true
